name: Local runner test

on:
  workflow_dispatch:
  push:
    branches: [ "feature" ]
jobs:
  testRunner:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2.0.0
    - name: Display Terraform Version
      run: terraform --version
    - name: Display Azure-CLI Version
      run: az --version
